[project]
name = "panochive"
maintainers = [
    { name = "Eric Phetteplace", email = "phette23@gmail.com" }
]
version = "0.1.0"
description = "Archive Panopto sessions"
license = "ECL-2.0"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "click==8.4.1",
    "oauthlib>=3.3.1",
    "pydantic>=2.13.4",
    "requests==2.34.2",
    "requests-oauthlib>=2.0.0",
    "rich>=15.0.0",
]

[project.scripts]
panochive = "panochive.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff==0.15.14",
]
